services:
  api:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - ./.env
    entrypoint: ["/bin/sh", "/app/docker-entrypoint.sh"]
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: